# OBJECTS DETECTION 

In [2]:
import cv2

# img = cv2.imread('test_imgs/riad.jpg')
cap = cv2.VideoCapture(0)
cap.set(3,640)
cap.set(4,480)

classNames =[]
classFile = 'coco.names'
with open(classFile,'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weightsPath = 'frozen_inference_graph.pb'

net = cv2.dnn_DetectionModel(weightsPath,configPath)
net.setInputSize(320,320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5,127.5,127.5))
net.setInputSwapRB(True)

while True:
    success,img = cap.read()
    classIds, confs, bbox = net.detect(img,confThreshold=0.5)
    print(classIds,bbox)
    
    if len(classIds) != 0:
        for classId,confidence,box in zip(classIds.flatten(),confs.flatten(),bbox):
            cv2.rectangle(img,box,color=(0,255,0),thickness=2)
            cv2.putText(img,classNames[classId-1].upper(),(box[0]+10,box[1]+30),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)
            cv2.putText(img,str(confidence),(box[0]+50,box[1]+50),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)

    cv2.imshow("Output",img)
    cv2.waitKey(1)


[[ 1]
 [73]
 [62]
 [62]
 [67]] [[275   0 365 480]
 [ 50 343  72  53]
 [125 358 101 117]
 [ 50 343  72  53]
 [ 47 346 202  60]]
[[ 1]
 [67]
 [62]
 [62]
 [62]] [[265   0 375 476]
 [ 39 347 217  58]
 [124 359 101 116]
 [ 45 343  78  53]
 [165 358  94 114]]
[[ 1]
 [67]
 [67]
 [62]
 [62]
 [62]] [[259   0 381 477]
 [ 38 346 217  57]
 [ 40 342 203 134]
 [123 350 101 125]
 [165 355  95 119]
 [ 50 330  46  28]]
[[ 1]
 [67]
 [62]
 [67]
 [62]] [[253   6 386 474]
 [ 39 346 216  57]
 [123 349 102 126]
 [ 40 344 206 132]
 [165 354  96 120]]
[[ 1]
 [67]
 [67]
 [62]
 [62]
 [62]] [[255   3 384 477]
 [ 37 347 219  56]
 [ 41 345 207 131]
 [122 353 103 121]
 [165 355  96 119]
 [ 51 332  45  26]]
[[ 1]
 [67]
 [67]
 [62]
 [62]
 [62]] [[254   3 385 476]
 [ 37 347 219  56]
 [ 40 346 207 130]
 [123 352 102 123]
 [166 355  95 120]
 [ 52 333  44  24]]
[[ 1]
 [67]
 [67]
 [62]
 [62]
 [62]] [[270   0 370 480]
 [ 37 347 217  56]
 [ 39 345 208 131]
 [ 50 331  47  28]
 [122 352 103 122]
 [165 354  97 121]]
[[ 1]
 [67]

[[ 1]
 [67]
 [62]
 [67]
 [62]] [[238   0 395 480]
 [ 37 343 217  61]
 [124 347 102 128]
 [ 21 351 224 126]
 [165 354  96 119]]
[[ 1]
 [67]
 [62]
 [ 1]
 [67]
 [62]] [[237   0 395 480]
 [ 37 342 217  62]
 [124 346 100 129]
 [128 332 102 142]
 [ 21 349 224 128]
 [165 355  95 118]]
[[ 1]
 [ 1]
 [62]
 [67]
 [67]
 [ 1]
 [62]] [[232   0 399 480]
 [127 331 104 142]
 [124 344 102 131]
 [ 20 352 225 125]
 [ 40 341 212  63]
 [151 337 105 131]
 [163 355  96 117]]
[[ 1]
 [62]
 [ 1]
 [67]
 [67]
 [62]] [[218   1 415 479]
 [124 346 102 129]
 [128 333 104 140]
 [ 19 353 227 124]
 [ 42 342 212  62]
 [162 356  95 116]]
[[ 1]
 [62]
 [67]
 [67]
 [ 1]
 [62]] [[220   0 413 480]
 [125 347 100 128]
 [ 42 342 209  62]
 [ 19 350 224 127]
 [133 325 102 143]
 [164 355  93 117]]
[[ 1]
 [72]
 [62]
 [ 1]
 [62]
 [67]] [[262  58 364 410]
 [345 237 105  92]
 [123 346 102 129]
 [133 325 102 143]
 [166 354  94 120]
 [ 21 350 219 128]]
[[ 1]
 [72]
 [67]
 [62]
 [67]
 [62]
 [62]] [[232   0 400 480]
 [342 234 107  92]
 [ 34 3

[[77]
 [ 1]
 [ 1]
 [73]] [[223 105 319 281]
 [250  19 387 460]
 [418   7 222 297]
 [ 56 337  66  58]]
[[77]
 [73]
 [ 1]] [[253 105 288 333]
 [ 56 338  66  56]
 [293  29 342 438]]
[[ 1]
 [75]
 [77]
 [73]] [[246   0 392 479]
 [252 189 274 283]
 [252 185 282 286]
 [258 187 291 285]]
[[ 1]
 [67]
 [62]
 [73]] [[211   3 424 477]
 [ 52 343 196  59]
 [126 348  99 127]
 [ 56 339  64  56]]
[[ 1]
 [73]] [[212   3 423 477]
 [ 55 339  67  56]]
[[ 1]
 [67]
 [62]] [[288   0 352 480]
 [ 45 344 204  60]
 [122 349 104 126]]
[[77]
 [ 1]
 [67]
 [77]
 [62]] [[360 137 125 292]
 [314   0 326 480]
 [ 46 342 203  61]
 [362 141  88 162]
 [124 344 101 132]]
[[77]
 [77]
 [ 1]
 [67]
 [62]
 [62]] [[348 136 140 304]
 [352 139 104 170]
 [333   0 307 479]
 [ 45 342 204  61]
 [124 345 101 131]
 [ 48 331  78 145]]
[[77]
 [ 1]
 [67]
 [62]] [[317 152 163 297]
 [317   0 323 479]
 [ 48 343 201  61]
 [ 49 333  78 143]]
[[ 1]
 [77]
 [67]
 [62]] [[293   0 347 480]
 [335 120  64 153]
 [ 46 343 205  61]
 [124 346 100 130]]
[[ 1]

[[ 1]
 [67]
 [77]
 [62]
 [67]
 [67]
 [62]] [[239   1 397 479]
 [ 30 343 222  61]
 [376 100  51  70]
 [124 350 101 125]
 [ 37 343 212 131]
 [ 38 359 214  74]
 [ 32 332  94 139]]
[[ 1]
 [67]
 [62]
 [77]] [[235   1 402 479]
 [ 38 343 213  61]
 [125 350 100 125]
 [383 109  44  59]]
[[ 1]
 [67]
 [62]
 [67]
 [77]] [[235   1 402 479]
 [ 30 343 222  61]
 [124 348 101 127]
 [ 37 359 214  73]
 [384 108  44  59]]
[[ 1]
 [67]
 [62]
 [67]
 [67]] [[243   1 395 479]
 [ 31 344 222  60]
 [122 351 103 124]
 [ 33 343 216 131]
 [ 40 359 211  75]]
[[ 1]
 [67]
 [62]
 [67]] [[232   2 405 478]
 [ 33 343 218  61]
 [124 351 101 123]
 [ 41 360 210  74]]
[[ 1]
 [67]
 [62]
 [67]] [[236   1 401 479]
 [ 35 342 216  63]
 [125 350 100 124]
 [ 40 360 211  72]]
[[ 1]
 [67]
 [62]
 [67]] [[242   1 396 479]
 [ 36 342 215  63]
 [125 350 100 124]
 [ 39 360 211  75]]
[[ 1]
 [67]
 [62]
 [67]] [[241   1 397 479]
 [ 37 343 214  62]
 [123 351 102 124]
 [ 41 360 210  73]]
[[ 1]
 [67]
 [62]
 [67]
 [77]
 [67]] [[245   1 394 479]
 [ 

[[77]
 [ 1]
 [62]
 [62]
 [ 1]
 [67]
 [77]] [[325  58 193 385]
 [288   3 352 471]
 [ 34 333  92 143]
 [123 343 102 133]
 [126 335 103 141]
 [ 42 342 209  62]
 [337  72 154 282]]
[[77]
 [ 1]
 [67]
 [62]
 [62]
 [ 1]
 [67]] [[331  55 182 376]
 [281   0 359 473]
 [ 40 342 211  62]
 [ 36 333  92 144]
 [123 341 102 135]
 [127 332 103 144]
 [ 44 359 209  78]]
[[77]
 [ 1]
 [77]
 [ 1]
 [77]
 [67]
 [62]
 [62]
 [67]] [[322  43 198 404]
 [295   0 340 480]
 [331  54 152 292]
 [127 331 103 144]
 [318  59 108 166]
 [ 41 342 210  61]
 [123 341 104 135]
 [ 36 333  91 145]
 [ 45 359 208  77]]
[[77]
 [ 1]
 [67]
 [62]] [[318  46 156 278]
 [253   0 386 478]
 [ 35 342 217  61]
 [124 346 101 129]]
[[77]
 [ 1]
 [77]
 [67]
 [62]
 [77]
 [ 1]] [[335  47 146 277]
 [259   1 381 478]
 [337  45 214 367]
 [ 40 343 212  61]
 [123 342 103 133]
 [319  46 100 161]
 [127 332 103 142]]
[[77]
 [ 1]
 [77]
 [67]
 [62]] [[358  48 167 350]
 [262   2 378 475]
 [332  57  97 152]
 [ 37 342 216  61]
 [124 344 101 132]]
[[77]
 [ 1]
 

[[77]
 [ 1]
 [ 1]
 [62]
 [ 1]] [[211  92 218 365]
 [181  10 452 468]
 [146 327  42  46]
 [ 36 330  92 145]
 [  0 301  43 150]]
[[77]
 [ 1]
 [ 1]
 [73]
 [62]
 [ 1]] [[209  92 214 357]
 [175   8 457 469]
 [146 327  43  48]
 [ 55 339  70  53]
 [ 36 330  93 144]
 [  1 301  44 153]]
[[77]
 [ 1]
 [ 1]
 [73]] [[212  93 210 357]
 [177   6 455 471]
 [147 327  42  46]
 [ 54 340  71  52]]
[[77]
 [ 1]
 [ 1]
 [73]] [[213  93 212 351]
 [179   7 454 471]
 [147 327  42  48]
 [ 54 340  70  52]]
[[77]
 [ 1]
 [ 1]
 [73]] [[213  93 211 360]
 [185   6 449 473]
 [147 327  42  48]
 [ 53 339  71  53]]
[[77]
 [ 1]
 [ 1]
 [73]] [[207  93 219 363]
 [181   8 451 470]
 [146 326  45  50]
 [ 53 340  72  53]]
[[77]
 [ 1]
 [ 1]] [[193  97 235 370]
 [179   9 456 470]
 [146 325  43  50]]
[[77]
 [ 1]
 [75]
 [77]] [[145 145 246 326]
 [152   2 486 477]
 [145 147 251 326]
 [159  95 379 382]]
[[ 1]
 [ 1]
 [67]
 [62]] [[261   3 379 475]
 [151 327  33  44]
 [ 67 360 171  80]
 [ 38 344  92 131]]
[[ 1]
 [73]
 [ 1]
 [ 1]
 [62]
 [

[[ 1]
 [62]
 [ 1]
 [ 1]
 [67]
 [67]
 [62]] [[267   1 373 479]
 [127 347  95 128]
 [130 334  98 139]
 [150 325  41  50]
 [ 45 340 206  66]
 [ 50 361 202  75]
 [ 98 353  99 123]]
[[ 1]
 [ 1]
 [62]
 [ 1]
 [67]
 [ 1]
 [67]
 [62]
 [62]] [[248   0 392 480]
 [129 331  97 142]
 [125 343  97 132]
 [149 325  41  52]
 [ 48 340 207  65]
 [  2 304  49 154]
 [ 53 361 203  76]
 [101 346  96 130]
 [165 354  92 121]]
[[ 1]
 [77]
 [ 1]
 [62]
 [ 1]
 [67]
 [67]
 [62]
 [62]] [[233   1 406 479]
 [412 164 186 131]
 [130 331  97 143]
 [126 346  97 129]
 [150 324  41  52]
 [ 50 360 205  80]
 [ 47 341 208  65]
 [ 99 349  97 128]
 [164 355  93 121]]
[[ 1]
 [62]
 [77]
 [ 1]
 [62]
 [67]
 [67]
 [ 1]] [[232   1 407 479]
 [125 347  97 128]
 [414 166 176 131]
 [129 331  97 144]
 [101 353  96 124]
 [ 50 361 206  77]
 [ 49 341 206  65]
 [149 323  43  52]]
[[ 1]
 [62]
 [62]
 [ 1]
 [77]
 [67]
 [ 1]
 [67]
 [62]] [[239   1 401 479]
 [ 32 327  91 146]
 [126 347  96 129]
 [130 332  97 143]
 [441 152 105 113]
 [ 48 361 207  76

[[ 1]
 [ 1]
 [77]
 [67]
 [ 1]
 [ 1]] [[207   6 430 473]
 [133 328 100 138]
 [431 126  59  69]
 [ 51 365 198  66]
 [144 324  61  55]
 [106 338  92 138]]
[[ 1]
 [ 1]
 [77]
 [ 1]
 [67]
 [77]
 [67]] [[147 324 108 136]
 [206   9 432 470]
 [386 101  83 120]
 [145 322  58  53]
 [ 50 363 203  66]
 [418 110  83 112]
 [ 57 340 197  65]]
[[ 1]
 [ 1]
 [77]
 [ 1]
 [67]] [[206   9 430 470]
 [134 325  98 141]
 [331  52  67 133]
 [146 322  55  51]
 [ 50 363 198  65]]
[[ 1]
 [62]] [[183   5 449 473]
 [125 335  97 141]]
[[ 1]
 [ 1]
 [75]] [[203   0 437 480]
 [160 322  99 138]
 [  9 190 154 256]]
[[ 1]
 [ 1]
 [ 1]
 [67]
 [67]
 [ 1]] [[259   2 381 476]
 [140 320  64  53]
 [130 326  97 148]
 [ 31 344 194  63]
 [ 25 360 194  68]
 [142 316 113 139]]
[[ 1]
 [67]
 [67]
 [67]
 [ 1]] [[258   2 382 476]
 [ 32 343 188  65]
 [ 26 360 194  68]
 [ 40 344 212 130]
 [127 331 102 144]]
[[ 1]
 [67]
 [67]] [[260   2 380 475]
 [ 42 343 211 132]
 [ 33 343 188  66]]
[[ 1]
 [67]
 [67]] [[260   1 380 477]
 [ 42 338 211 137]
 [

[[ 1]
 [ 1]
 [67]] [[261   1 379 477]
 [150 324 107 149]
 [ 32 342 189  64]]
[[ 1]
 [77]
 [62]] [[145   8 492 471]
 [ 75 104 295 357]
 [ 31 332 107 146]]
[[77]
 [ 1]
 [77]
 [ 1]] [[238  29 212 291]
 [218   3 413 477]
 [243  32 131 144]
 [130 326 100 145]]
[[77]
 [77]
 [ 1]
 [ 1]
 [ 1]
 [ 1]
 [77]] [[340  57 167 205]
 [326  51 112 118]
 [149 326 104 132]
 [224   8 413 472]
 [150 327  62  49]
 [312  28 317 341]
 [343  42 248 250]]
[[77]
 [ 1]
 [ 1]
 [77]
 [67]
 [ 1]
 [62]
 [77]
 [62]
 [ 1]] [[382  88  91  97]
 [208   3 429 477]
 [152 324  57  48]
 [369  97  93 112]
 [ 39 343 213  61]
 [155 320  99 132]
 [129 346  92 129]
 [382  99  97 146]
 [ 33 332  92 144]
 [133 333  95 141]]
[[ 1]
 [ 1]
 [77]
 [ 1]
 [62]
 [ 1]
 [67]] [[204   4 433 475]
 [151 322  59  50]
 [394 131  88 100]
 [156 329  99 137]
 [129 349  91 127]
 [133 335  93 139]
 [ 24 361 196  72]]
[[ 1]
 [77]
 [77]
 [ 1]
 [77]
 [67]
 [62]
 [62]] [[246   1 394 479]
 [414 138 102 126]
 [395 142  84  95]
 [157 327  41  37]
 [397 132 150

[[ 1]
 [ 1]
 [62]] [[252   0 388 480]
 [155 325  38  38]
 [156 363 104 110]]
[[77]
 [ 1]
 [77]] [[148 147 221 305]
 [149   2 490 475]
 [149 145 171 226]]
[[ 1]
 [77]
 [77]
 [75]
 [ 1]
 [62]
 [ 1]
 [67]] [[225   5 411 475]
 [256  55 129 150]
 [250  56 180 316]
 [403 252  51  48]
 [  2 313  80 158]
 [126 351 100 124]
 [221  43 230 396]
 [ 46 345 207  61]]
[[77]
 [77]
 [ 1]
 [77]
 [ 1]
 [ 1]
 [67]
 [ 1]
 [62]
 [67]] [[321  52 103 117]
 [340  59 136 254]
 [210   4 426 475]
 [325  53 115 161]
 [155 325  39  40]
 [  2 314  77 156]
 [ 49 345 198  61]
 [132 337  94 132]
 [127 356  94 119]
 [ 55 362 192  67]]
[[77]
 [ 1]
 [77]
 [ 1]
 [ 1]
 [67]
 [77]
 [62]
 [ 1]
 [62]
 [67]] [[347  74  94 116]
 [214   3 422 477]
 [339  87  87 128]
 [155 324  40  42]
 [  2 314  75 152]
 [ 53 345 195  61]
 [365  69 103 185]
 [128 357  92 118]
 [132 339  95 129]
 [102 362  94 115]
 [101 361 155  74]]
[[77]
 [ 1]
 [ 1]
 [ 1]
 [62]
 [ 1]
 [ 1]
 [62]
 [67]
 [ 1]
 [ 1]] [[357 100  90 105]
 [205   4 432 475]
 [153 324 

[[ 1]
 [67]
 [85]
 [67]
 [62]
 [67]] [[233   3 405 477]
 [ 40 348 214  57]
 [577 421  53  54]
 [ 52 363 202  67]
 [126 351 101 123]
 [ 31 349 221 126]]
[[ 1]
 [62]
 [67]
 [67]
 [62]
 [62]] [[260   1 380 479]
 [125 352  99 123]
 [ 47 347 205  58]
 [ 54 362 198  70]
 [101 357 100 120]
 [162 353  94 121]]
[[ 1]
 [67]
 [62]
 [67]
 [67]] [[246   0 394 480]
 [ 40 347 214  58]
 [125 352 100 123]
 [ 50 361 205  69]
 [ 26 350 225 126]]
[[ 1]
 [67]
 [62]
 [67]
 [62]] [[242   0 398 480]
 [ 45 346 207  59]
 [126 351  99 124]
 [ 52 361 202  70]
 [101 358  98 119]]
[[ 1]
 [67]
 [62]
 [67]
 [62]
 [62]
 [62]] [[241   0 399 480]
 [ 48 348 205  57]
 [127 351  98 124]
 [ 55 361 198  69]
 [  4 325  86 145]
 [100 357 100 120]
 [160 353  97 121]]
[[ 1]
 [62]
 [67]
 [67]
 [62]] [[262   0 378 480]
 [125 352  99 123]
 [ 47 348 208  58]
 [ 55 361 200  71]
 [101 359 100 118]]
[[ 1]
 [67]
 [62]
 [67]
 [62]
 [67]
 [62]] [[242   1 398 479]
 [ 44 347 209  59]
 [124 351 101 124]
 [ 53 361 201  71]
 [101 358 100 119]


KeyboardInterrupt: 

### From single image

In [1]:
import cv2

img = cv2.imread('test_imgs/desk.jpg')

classNames =[]
classFile = 'coco.names'
with open(classFile,'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weightsPath = 'frozen_inference_graph.pb'

net = cv2.dnn_DetectionModel(weightsPath,configPath)
net.setInputSize(320,320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5,127.5,127.5))
net.setInputSwapRB(True)

classIds, confs, bbox = net.detect(img,confThreshold=0.5)
print(classIds,bbox)

for classId,confidence,box in zip(classIds.flatten(),confs.flatten(),bbox):
    cv2.rectangle(img,box,color=(0,255,0),thickness=2)
    cv2.putText(img,classNames[classId-1].upper(),(box[0]+10,box[1]+30),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)

cv2.imshow("Output",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[72]
 [76]
 [74]
 [74]] [[108  25 123 119]
 [134 158 174  55]
 [120 151  30  17]
 [222 129  29  27]]


# FACE ONLY

In [2]:
import cv2

# Load the cascade
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# To capture video from webcam. 
cap = cv2.VideoCapture(0)
# To use a video file as input 
# cap = cv2.VideoCapture('filename.mp4')

while True:
    # Read the frame
    _, img = cap.read()
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Detect the faces
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)
    # Draw the rectangle around each face
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
    # Display
    cv2.imshow('img', img)
    # Stop if escape key is pressed
    k = cv2.waitKey(30) & 0xff
    if k==27:
        break
# Release the VideoCapture object
cap.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 

# Face & eyes

In [1]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye.xml')

while True:
    ret, frame = cap.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 5)
        roi_gray = gray[y:y+w, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.3, 5)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 5)

    cv2.imshow('frame', frame)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 