# OBJECTS DETECTION 

In [6]:
import cv2

# img = cv2.imread('test_imgs/riad.jpg')
cap = cv2.VideoCapture(0)
cap.set(3,640)
cap.set(4,480)

classNames =[]
classFile = 'coco.names'
with open(classFile,'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weightsPath = 'frozen_inference_graph.pb'

net = cv2.dnn_DetectionModel(weightsPath,configPath)
net.setInputSize(320,320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5,127.5,127.5))
net.setInputSwapRB(True)

while True:
    success,img = cap.read()
    classIds, confs, bbox = net.detect(img,confThreshold=0.5)
    print(classIds,bbox)
    
    if len(classIds) != 0 :
        for classId,confidence,box in zip(classIds.flatten(),confs.flatten(),bbox):
            if classId == 77 : # show cell phone ONLY
                cv2.rectangle(img,box,color=(0,255,0),thickness=2)
                cv2.putText(img,classNames[classId-1].upper()+': '+str(round(confidence*100))+'%',(box[0]+10,box[1]+30),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)

    cv2.imshow("Output",img)
    cv2.waitKey(1)


[[1]
 [1]] [[ 42   6 585 469]
 [333  21 306 442]]
[[ 1]
 [18]] [[287   1 348 479]
 [292   0 343 480]]
[[ 1]
 [18]] [[287   0 345 480]
 [296   0 337 480]]
[[1]] [[300   2 338 478]]
[[ 1]
 [17]] [[310   1 327 478]
 [303   0 335 480]]
[[1]] [[307   1 330 479]]
[[1]] [[309   0 327 480]]
[[1]] [[311   2 325 478]]
[[ 1]
 [17]] [[309   1 328 478]
 [303   0 335 480]]
[[ 1]
 [17]] [[311   2 325 478]
 [304   0 333 480]]
[[1]] [[317   4 323 474]]
[[1]] [[324   4 316 475]]
[[1]
 [1]] [[318   4 322 475]
 [180   3 414 475]]
[[1]
 [1]] [[320   3 320 475]
 [173   2 408 477]]
[[ 1]
 [17]] [[304   2 333 478]
 [304   0 333 480]]
[[ 1]
 [17]
 [18]] [[279   0 354 480]
 [293   0 341 477]
 [293   0 341 477]]
[[ 1]
 [18]
 [17]] [[279   0 354 480]
 [291  37 346 439]
 [291  37 346 439]]
[[18]
 [ 1]
 [17]] [[291  18 348 459]
 [281   0 353 480]
 [291  18 348 459]]
[[75]
 [ 1]] [[297 300 171 174]
 [303   1 337 479]]
[[75]
 [77]
 [ 1]
 [ 1]] [[213 227 230 253]
 [217 231 224 249]
 [ 88   0 541 480]
 [311   0 329 479

[[77]
 [77]
 [ 1]] [[353 110 178 328]
 [104 143 205 267]
 [ 63  11 570 465]]
[[77]
 [77]
 [ 1]] [[353 110 178 329]
 [109 144 197 267]
 [ 68  10 565 466]]
[[77]
 [77]
 [ 1]] [[353 112 176 325]
 [110 143 194 266]
 [ 71  11 563 465]]
[[77]
 [77]
 [75]
 [ 1]] [[357 112 173 324]
 [110 143 194 263]
 [110 143 194 263]
 [ 75  14 558 462]]
[[77]
 [77]
 [ 1]] [[356 113 174 321]
 [109 144 195 266]
 [ 75  15 558 460]]
[[77]
 [77]
 [ 1]] [[354 110 175 326]
 [111 143 191 259]
 [ 73   6 560 470]]
[[77]
 [77]
 [ 1]] [[354 111 176 331]
 [ 96 142 221 265]
 [ 72   9 562 467]]
[[77]
 [77]
 [ 1]] [[356 110 173 337]
 [ 76 141 243 253]
 [ 65   4 570 474]]
[[77]
 [77]
 [ 1]] [[354 113 176 327]
 [ 66 149 262 252]
 [ 58   8 575 468]]
[[77]
 [77]
 [ 1]] [[355 114 175 330]
 [ 74 143 249 248]
 [ 59   8 575 469]]
[[77]
 [77]
 [ 1]] [[355 113 176 328]
 [ 71 150 259 248]
 [ 66   8 568 468]]
[[77]
 [77]
 [ 1]] [[355 113 174 341]
 [ 71 147 262 254]
 [ 61   5 573 472]]
[[77]
 [77]
 [ 1]] [[354 114 177 324]
 [ 71 147 262

KeyboardInterrupt: 

### From single image

In [1]:
import cv2

img = cv2.imread('test_imgs/desk.jpg')

classNames =[]
classFile = 'coco.names'
with open(classFile,'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weightsPath = 'frozen_inference_graph.pb'

net = cv2.dnn_DetectionModel(weightsPath,configPath)
net.setInputSize(320,320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5,127.5,127.5))
net.setInputSwapRB(True)

classIds, confs, bbox = net.detect(img,confThreshold=0.5)
print(classIds,bbox)

for classId,confidence,box in zip(classIds.flatten(),confs.flatten(),bbox):
    cv2.rectangle(img,box,color=(0,255,0),thickness=2)
    cv2.putText(img,classNames[classId-1].upper(),(box[0]+10,box[1]+30),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)

cv2.imshow("Output",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[72]
 [76]
 [74]
 [74]] [[108  25 123 119]
 [134 158 174  55]
 [120 151  30  17]
 [222 129  29  27]]


# FACE ONLY

In [1]:
import cv2

# Load the cascade
face_cascade = cv2.CascadeClassifier('haarcascade_frontalface_default.xml')

# To capture video from webcam. 
cap = cv2.VideoCapture(0)
# To use a video file as input 
# cap = cv2.VideoCapture('filename.mp4')

while True:
    # Read the frame
    _, img = cap.read()
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Detect the faces
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)
    # Draw the rectangle around each face
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
    # Display
    cv2.imshow('img', img)
    # Stop if escape key is pressed
    k = cv2.waitKey(30) & 0xff
    if k==27:
        break
# Release the VideoCapture object
cap.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 

# Face & eyes

In [ ]:
import numpy as np
import cv2

cap = cv2.VideoCapture(0)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye_tree_eyeglasses.xml')

while True:
    ret, frame = cap.read()

    gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 5)
        roi_gray = gray[y:y+w, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.3, 5)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 5)

    cv2.imshow('frame', frame)

    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

# Eyes!!  -   No eyes!!

In [2]:
import cv2
eye_cascPath = 'haarcascade_eye_tree_eyeglasses.xml'  #eye detect model
face_cascPath = 'haarcascade_frontalface_alt.xml'  #face detect model
faceCascade = cv2.CascadeClassifier(face_cascPath)
eyeCascade = cv2.CascadeClassifier(eye_cascPath)

cap = cv2.VideoCapture(0)
while 1:
    ret, img = cap.read()
    if ret:
        frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        # Detect faces in the image
        faces = faceCascade.detectMultiScale(
            frame,
            scaleFactor=1.1,
            minNeighbors=5,
            minSize=(30, 30),
            # flags = cv2.CV_HAAR_SCALE_IMAGE
        )
        # print("Found {0} faces!".format(len(faces)))
        if len(faces) > 0:
            # Draw a rectangle around the faces
            for (x, y, w, h) in faces:
                cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)
            frame_tmp = img[faces[0][1]:faces[0][1] + faces[0][3], faces[0][0]:faces[0][0] + faces[0][2]:1, :]
            frame = frame[faces[0][1]:faces[0][1] + faces[0][3], faces[0][0]:faces[0][0] + faces[0][2]:1]
            eyes = eyeCascade.detectMultiScale(
                frame,
                scaleFactor=1.1,
                minNeighbors=5,
                minSize=(30, 30),
                # flags = cv2.CV_HAAR_SCALE_IMAGE
            )
            if len(eyes) == 0:
                print('no eyes!!!')
            else:
                print('eyes!!!')
            frame_tmp = cv2.resize(frame_tmp, (400, 400), interpolation=cv2.INTER_LINEAR)
            cv2.imshow('Face Recognition', frame_tmp)
        waitkey = cv2.waitKey(1)
        if waitkey == ord('q') or waitkey == ord('Q'):
            cv2.destroyAllWindows()
            break

no eyes!!!
no eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
no eyes!!!
no eyes!!!
eyes!!!
eyes!!!
eyes!!!
no eyes!!!
no eyes!!!
no eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
no eyes!!!
no eyes!!!
no eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
no eyes!!!
no eyes!!!
no eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
no eyes!!!
no eyes!!!
eyes!!!
no eyes!!!
eyes!!!
no eyes!!!
no eyes!!!
no eyes!!!
no eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes

KeyboardInterrupt: 