# OBJECTS DETECTION 

In [3]:
import cv2

# img = cv2.imread('test_imgs/riad.jpg')
cap = cv2.VideoCapture(1)
cap.set(3,640)
cap.set(4,480)

classNames =[]
classFile = 'coco.names'
with open(classFile,'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weightsPath = 'frozen_inference_graph.pb'

net = cv2.dnn_DetectionModel(weightsPath,configPath)
net.setInputSize(320,320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5,127.5,127.5))
net.setInputSwapRB(True)

while True:
    success,img = cap.read()
    classIds, confs, bbox = net.detect(img,confThreshold=0.5)
    print(classIds,bbox)
    
    if len(classIds) != 0 :
        for classId,confidence,box in zip(classIds.flatten(),confs.flatten(),bbox):
#             if classId == 77 : # show cell phone ONLY
            cv2.rectangle(img,box,color=(0,255,0),thickness=2)
            cv2.putText(img,classNames[classId-1].upper()+': '+str(round(confidence*100))+'%',(box[0]+10,box[1]+30),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)
    cv2.imshow("Output",img)
    if cv2.waitKey(10)== ord('q'):
        break
cap.release()
cv2.destroyAllWindows()

() ()
[[1]] [[  7   2 630 476]]
[[1]] [[  7   2 629 476]]
[[1]] [[  8   2 628 476]]
[[1]] [[  6   2 630 476]]
[[1]] [[  7   2 629 476]]
[[1]] [[  7   2 630 476]]
[[1]] [[  7   2 630 477]]
[[1]] [[ 30   2 607 477]]
[[ 1]
 [77]] [[ 28   3 602 476]
 [251 307 103 103]]
[[ 1]
 [77]] [[ 27   4 598 476]
 [274 324  99 102]]
[[ 1]
 [77]] [[ 29   0 610 480]
 [307 357 104 114]]
[[ 1]
 [77]] [[ 28   2 611 477]
 [340 392 110  88]]
[[1]] [[ 31   2 608 478]]
[[1]] [[ 30   3 610 477]]
[[1]] [[ 31   3 609 477]]
[[1]] [[ 31   4 609 476]]
[[1]] [[ 28   2 612 478]]
[[1]] [[ 28   1 612 479]]
[[1]] [[ 28   4 612 476]]
[[1]] [[ 29   3 610 477]]
[[1]] [[ 34   1 606 479]]
[[1]] [[ 40   0 600 480]]
[[1]] [[ 24   0 616 480]]
[[1]
 [1]] [[ 48   3 592 477]
 [  2 249 152 230]]
[[1]] [[ 39   1 601 479]]
[[1]] [[ 40   2 600 478]]
[[1]] [[ 40   2 600 478]]
[[1]] [[ 41   1 599 479]]
[[1]] [[ 44   1 596 479]]
[[1]] [[ 42   1 598 479]]
[[1]] [[ 43   1 597 479]]
[[1]] [[ 45   1 595 479]]
[[1]] [[ 46   1 594 479]]
[[1]] [[

### From single image

In [21]:
def increase_brightness(img, value=30):
    hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV)
    h, s, v = cv2.split(hsv)

    lim = 255 - value
    v[v > lim] = 255
    v[v <= lim] += value

    final_hsv = cv2.merge((h, s, v))
    img = cv2.cvtColor(final_hsv, cv2.COLOR_HSV2BGR)
    return img

In [40]:
img = cv2.imread('test_imgs/desk.jpg') #load rgb image
img = increase_brightness(img, 999)
cv2.imshow("Output",img)
cv2.waitKey(0)

-1

In [11]:
import cv2

img = cv2.imread('test_imgs/desk.jpg')

classNames =[]
classFile = 'coco.names'
with open(classFile,'rt') as f:
    classNames = f.read().rstrip('\n').split('\n')

configPath = 'ssd_mobilenet_v3_large_coco_2020_01_14.pbtxt'
weightsPath = 'frozen_inference_graph.pb'

net = cv2.dnn_DetectionModel(weightsPath,configPath)
net.setInputSize(320,320)
net.setInputScale(1.0/127.5)
net.setInputMean((127.5,127.5,127.5))
net.setInputSwapRB(True)

classIds, confs, bbox = net.detect(img,confThreshold=0.5)
print(classIds,bbox)

for classId,confidence,box in zip(classIds.flatten(),confs.flatten(),bbox):
    cv2.rectangle(img,box,color=(0,255,0),thickness=2)
    cv2.putText(img,classNames[classId-1].upper(),(box[0]+10,box[1]+30),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)

cv2.imshow("Output",img)
cv2.waitKey(0)
cv2.destroyAllWindows()

[[72]
 [76]
 [74]
 [74]] [[108  25 123 119]
 [134 158 174  55]
 [120 151  30  17]
 [222 129  29  27]]


error: OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-q3d_8t8e\opencv\modules\imgproc\src\color.cpp:182: error: (-215:Assertion failed) !_src.empty() in function 'cv::cvtColor'


# FACE ONLY

In [5]:
import cv2

# Load the cascade
face_cascade = cv2.CascadeClassifier('haarcascades/haarcascade_frontalface_default.xml')

# To capture video from webcam. 
cap = cv2.VideoCapture(0)
# To use a video file as input 
# cap = cv2.VideoCapture('filename.mp4')

while True:
    # Read the frame
    _, img = cap.read()
    # Convert to grayscale
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    # Detect the faces
    faces = face_cascade.detectMultiScale(gray, 1.1, 4)
    # Draw the rectangle around each face
    for (x, y, w, h) in faces:
        cv2.rectangle(img, (x, y), (x+w, y+h), (255, 0, 0), 2)
    # Display
    cv2.imshow('img', gray)
    # Stop if escape key is pressed
    k = cv2.waitKey(30) & 0xff
    if k==27:
        break
# Release the VideoCapture object
cap.release()
cv2.destroyAllWindows()

KeyboardInterrupt: 

In [ ]:
img = cv2.imread('test.jpg') #load rgb image
hsv = cv2.cvtColor(img, cv2.COLOR_BGR2HSV) #convert it to hsv

for x in range(0, len(hsv)):
    for y in range(0, len(hsv[0])):
        hsv[x, y][2] += value

img = cv2.cvtColor(hsv, cv2.COLOR_HSV2BGR)

# Face & eyes

In [57]:
import numpy as np
import cv2

cap = cv2.VideoCapture(2)
face_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_frontalface_default.xml')
eye_cascade = cv2.CascadeClassifier(cv2.data.haarcascades + 'haarcascade_eye_tree_eyeglasses.xml')

while True:
    ret, frame = cap.read()
    img = increase_brightness(frame, 50)
    gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
    faces = face_cascade.detectMultiScale(gray, 1.3, 5)
    for (x, y, w, h) in faces:
        cv2.rectangle(frame, (x, y), (x + w, y + h), (255, 0, 0), 5)
        roi_gray = gray[y:y+w, x:x+w]
        roi_color = frame[y:y+h, x:x+w]
        eyes = eye_cascade.detectMultiScale(roi_gray, 1.3, 5)
        for (ex, ey, ew, eh) in eyes:
            cv2.rectangle(roi_color, (ex, ey), (ex + ew, ey + eh), (0, 255, 0), 5)
        if len(eyes) == 0:
            cv2.putText(frame,'No eyes!!!',(50,50),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)
        else:
            cv2.putText(frame,'eyes!!!',(50,50),cv2.FONT_HERSHEY_COMPLEX,.8,(0,255,0),2)
    cv2.imshow('frame', frame)
    
    if cv2.waitKey(1) == ord('q'):
        break

cap.release()
cv2.destroyAllWindows()

# Eyes!!  -   No eyes!!

In [5]:
import cv2
eye_cascPath = 'haarcascades/haarcascade_eye_tree_eyeglasses.xml'  #eye detect model
face_cascPath = 'haarcascades/haarcascade_frontalface_alt.xml'  #face detect model
faceCascade = cv2.CascadeClassifier(face_cascPath)
eyeCascade = cv2.CascadeClassifier(eye_cascPath)

cap = cv2.VideoCapture(0)
while 1:
    ret, img = cap.read()
    if ret:
        frame = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)
        # Detect faces in the image
        faces = faceCascade.detectMultiScale(frame, 1.3, 5)
        # print("Found {0} faces!".format(len(faces)))
        if len(faces) > 0:
            # Draw a rectangle around the faces
            for (x, y, w, h) in faces:
                cv2.rectangle(img, (x, y), (x + w, y + h), (0, 255, 0), 2)
            frame_tmp = img[faces[0][1]:faces[0][1] + faces[0][3], faces[0][0]:faces[0][0] + faces[0][2]:1, :]
            frame = frame[faces[0][1]:faces[0][1] + faces[0][3], faces[0][0]:faces[0][0] + faces[0][2]:1]
            eyes = eyeCascade.detectMultiScale(
                frame,
                scaleFactor=1.1,
                minNeighbors=0,
                minSize=(30, 30),
                # flags = cv2.CV_HAAR_SCALE_IMAGE
            )
            if len(eyes) == 0:
                print('no eyes!!!')
            else:
                print('eyes!!!')
            frame_tmp = cv2.resize(frame_tmp, (400, 400), interpolation=cv2.INTER_LINEAR)
            cv2.imshow('Face Recognition', frame_tmp)
        waitkey = cv2.waitKey(1)
        if waitkey == ord('q') or waitkey == ord('Q'):
            cv2.destroyAllWindows()
            break

eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!
eyes!!!


In [1]:
import cv2
img = cv2.imread('test_imgs/riad.jpg')
cv2.imshow("Output",img)
cv2.waitKey(0)

-1